# -*- coding: utf-8 -*-
"""Conteúdo editorial dos 76 preenchedores (fonte: monografias PT1/PT2 + doc APP).
Níveis de indicação: 1 = 1ª escolha · 2 = forte · 3 = boa · 4 = seletiva.
Classes: A = 🔵🌸 integrativo dinâmico · M = 🟡 preenchedor · R = 🟣 estrutural · RV = 🟣🟢 estrutural maleável.
Flags: verif = dado em re-verificação (§6 do doc mestre) · pend = monografia pendente · ifu = contraindicações de bula listadas.
"""

PRODUTOS = [
# ---------------- FAMÍLIA AZUL 🔵🌸 — INTEGRATIVO DINÂMICO (34) ----------------
dict(k='Belotero Balance Lido', m='Belotero · Merz', t='CPM — Cohesive Polydensified Matrix; monofásico polidensificado*', c='A',
 comp='O gel mais fluido do banco e o maior tan δ (0,69): quase líquido em qualquer regime de movimento. Máxima integração, relevo praticamente nulo.',
 mp='Integração e naturalidade absolutas em tecido móvel',
 ind=[('Lábios naturais/delicados',2),('Linhas finas e perioral',2),('Regiões de alta dinâmica',2),('Sulcos superficiais (correção suave)',3)],
 ev=['Projeção e estrutura (mento, mandíbula, ângulo)','Terço médio estrutural','Olheiras sem dado de SF'],
 esc='Escolha quando a prioridade for o gel desaparecer no tecido — espalhar e acompanhar, sem criar relevo.',
 alt='Up Fine (G′ gêmeo, menos dissipativo) · Milimetric PRO Leve'),

dict(k='Up Fine Lido', m='UP · Ilikia', t='dados de plataforma não documentados no acervo', c='A', fl=['verif'],
 comp='G′ mínimo do banco (33,66 Pa) com tan δ moderado (0,36): espalha como o Balance, porém com um pouco mais de "gel".',
 mp='Microcorreções superficiais sem nenhum relevo',
 ind=[('Fronte',2),('Supercílio',2),('Têmpora superficial (difuso)',2),('Lábios muito naturais',3),('Sulcos superficiais',3),('Glabela (alerta vascular)',4)],
 ev=['Mento, mandíbula, zigoma','Grandes volumes'],
 esc='Escolha quando quiser preencher microrregiões com maleabilidade e integração máximas.',
 alt='Belotero Balance (mais dissipativo) · Neuramis Lido'),

dict(k='Milimetric PRO Leve Lido', m='Milimetric PRO', t='AH 20 mg/mL + lidocaína; reticulação DVS (literatura SBPqO)*', c='A',
 comp='Assinatura 56/32/0,57 — segunda maior dinâmica do banco. Refina e acompanha o movimento.',
 mp='Refinamento em regiões móveis',
 ind=[('Perioral',2),('Lábios (refinamento)',2),('Sulcos leves',3),('Sulco nasolabial inicial',3)],
 ev=['Estrutura e projeção','Olheiras "automáticas" (SF não medido)'],
 esc='Escolha quando a tarefa for ADAPTAR: microcorreção que precisa se mover junto.',
 alt='e.p.t.q S100 (par próximo) · Belotero Balance'),

dict(k='e.p.t.q S 100 Lido', m='e.p.t.q · Jetema', t='AH 24 mg/mL*', c='A',
 comp='70/39/0,56 — o degrau dinâmico da linha e.p.t.q: maleabilidade e movimento com mínimo corpo.',
 mp='Lábio natural e móvel',
 ind=[('Lábios delicados',1),('Perioral',2),('Linhas finas',2),('Fronte/supercílio',4)],
 ev=['Olheiras (24 mg/mL acima da faixa priorizada ~20)','Estrutura'],
 esc='Escolha quando quiser o lábio mais natural da linha: movimento antes de volume.',
 alt='Milimetric PRO Moderado (par quase idêntico) · Revanesse Kiss (mais corpo)'),

dict(k='Milimetric PRO Moderado Lido', m='Milimetric PRO', t='AH 20 mg/mL + lidocaína*', c='A',
 comp='72/35/0,48 — volume moderado que continua dançando com a mímica.',
 mp='Preencher com movimento',
 ind=[('Lábios (corpo)',2),('Vermelhão e contorno integrado',2),('Perioral',2),('Sulco nasolabial moderado',3),('Labiomentoniano/marionete',3),('Bochecha (tecido mole)',4),('Pré-jowl (vale)',4)],
 ev=['Estrutura e projeção','Olheiras sem SF'],
 esc='Escolha quando a tarefa for PREENCHER mantendo dinâmica — o meio-termo da linha.',
 alt='e.p.t.q S100 (par) · Juvéderm Ultra XC'),

dict(k='Rennova Fill Fine Lines Lido', m='Rennova', t='AH 24 mg/mL + lidocaína; 1,1 mL*', c='A',
 comp='82/44/0,53 — o menor G′ e o maior tan δ da família Rennova. Ferramenta de LINHA (microgeometria).',
 mp='Linhas finas e microcorreção superficial',
 ind=[('Linhas finas',1),('Periorais estáticas',2),('Pés de galinha',4),('Glabela (indicação oficial; ALTO risco vascular)',4)],
 ev=['Volume e estrutura','Olheiras'],
 esc='Escolha quando o defeito for uma LINHA, não um vale: correção de microgeometria.',
 alt='Restylane Refyne (mesmo G′, metade do tan δ) · Sofiderm Fine Lines'),

dict(k='Restylane Refyne Lido', m='Restylane · Galderma', t='OBT/XpresHAn*', c='A',
 comp='82/24/0,29 — flexível no movimento e estável no repouso (tan δ cai a 0,19 a 0,01 Hz). Espalha sem perder o lugar.',
 mp='Regiões dinâmicas superficiais com estabilidade',
 ind=[('Fronte',1),('Glabela (alerta vascular)',2),('Supercílio',2),('Têmpora (fanning subcutâneo)',2),('Sulco nasolabial superficial',3),('Marionete suave',3)],
 ev=['Projeção e estrutura'],
 esc='Escolha quando precisar de adaptação dinâmica que não migra: flexível ao sorrir, estável parado.',
 alt='Rennova Fine Lines (G′ igual, mais dissipativo) · Neuramis Lido'),

dict(k='Rennova Fill Eyes Lines Lido', m='Rennova', t='AH 24 mg/mL; 1,1 mL; Anvisa 80117580907*', c='A',
 comp='87/45/0,52 — desenhado para a região periorbicular: suavizar o vale do olhar com gel dinâmico.',
 mp='Periorbicular (indicação oficial da linha)',
 ind=[('Olheira/calha lacrimal (1ª da linha Rennova — SF não medido)',1),('Pés de galinha',2),('Olho afundado (indicação oficial)',3)],
 ev=['Não classificar como "baixo SF" sem medida','Volume estrutural'],
 esc='Escolha quando quiser suavizar o vale periorbicular com máxima adaptação — e monitore edema.',
 alt='Rennova Fine Lines (gêmeo) · Yvoire Contour+ (lógica oposta: projeção com precisão)'),

dict(k='Neuramis Lido', m='Neuramis · Medytox', t='dados de plataforma não atribuídos no acervo', c='A', fl=['verif'],
 comp='90/34/0,38 — espalhamento com baixo relevo; o abridor da linha Neuramis.',
 mp='Espalhar sem relevo em terço superior',
 ind=[('Fronte',1),('Glabela (alerta vascular)',2),('Supercílio',2),('Linhas superficiais',2),('Lábios muito delicados',4)],
 ev=['Estrutura','Preferir Neuramis Deep para lábios (escolha do autor)'],
 esc='Escolha quando a tarefa for ESPALHAR: correção plana em pele fina.',
 alt='Restylane Refyne · Up Fine'),

dict(k='Juvéderm Skinvive', m='Juvéderm · Allergan', t='Vycross VYC-12L; AH 12 mg/mL*', c='A',
 comp='102/55/0,54 em movimento — e o único gel do banco que cruza para líquido em repouso (tan δ 1,54 a 0,01 Hz). Não preenche: TRATA a superfície.',
 mp='Qualidade de pele (a terceira função: INTEGRAR)',
 ind=[('Qualidade cutânea das bochechas (microdepósitos intradérmicos — FDA)',1),('Linhas finas superficiais',2),('Perioral superficial',3),('Pescoço (conforme regulamentação local)',4)],
 ev=['Volumizar ou sustentar qualquer região','Lábios (volume)','Olheiras'],
 esc='Escolha quando o objetivo for tratar o tecido, não criar projeção — pele, não forma.',
 alt='Belotero Balance (integração dérmica) · skinboosters'),

dict(k='Juvéderm Ultra XC Lido', m='Juvéderm · Allergan', t='Hylacross; AH 24 mg/mL; alta coesividade declarada*', c='A',
 comp='111/37/0,34 — baixo G′ com coesividade declarada alta: prova de que integração e coesão podem coexistir.',
 mp='Preencher e integrar, não rigidificar',
 ind=[('Lábios (volume integrado)',2),('Vermelhão e contorno',2),('Perioral',2),('Sulco nasolabial',3)],
 ev=['Estrutura e projeção'],
 esc='Escolha quando quiser lábio com movimento e coesão — corpo suave que acompanha.',
 alt='Rennova Fill (par quase idêntico) · Ultra Plus XC (mais sustentação)'),

dict(k='Rennova Fill', m='Rennova', t='AH 23 mg/mL*', c='A',
 comp='118/41/0,35 — a ferramenta de DEPRESSÃO da linha: preenche o defeito raso com adaptação.',
 mp='Depressões leves a moderadas',
 ind=[('Sulco nasolabial leve/moderado',2),('Perioral',3),('Labiomentoniano',3),('Marionete inicial',3),('Pré-jowl pequeno',4)],
 ev=['Estrutura e vértice'],
 esc='Escolha quando o defeito for uma DEPRESSÃO rasa: FILL preenche, sem construir.',
 alt='Juvéderm Ultra XC (par) · Sofiderm Derm Plus'),

dict(k='Sofiderm Derm Plus', m='Sofiderm · Aeskins/Techderm', t='MCLPE; AH 20±3 mg/mL; partícula declarada 1500 µm; linha corporal*', c='A',
 comp='122/30/0,25 — o MENOR G′ de toda a família Sofiderm, mesmo com a 2ª maior partícula: "partícula maior não significa maior elasticidade". Corporal adaptativo.',
 mp='Correção corporal distribuída e precisa',
 ind=[('Irregularidades pós-lipoaspiração (vale corporal)',1),('Marcação abdominal (precisão geométrica)',2),('Cicatrizes deprimidas',2),('Peitoral (transições)',3),('Coxas/braços (refinamento de contorno)',3),('Áreas íntimas (indicação comercial)',4)],
 ev=['Grande projeção glútea (→ Sub-Skin)','Hip dips volumosos (→ Sub-Skin)','Vértice corporal','Nem toda irregularidade pós-lipo é indicação de filler (fibrose/aderência)'],
 esc='Escolha quando quiser corrigir e distribuir volume no corpo sem transformar a correção em estrutura.',
 alt='Sofiderm Sub-Skin (o estrutural corporal) · Rennova Fill (facial de G′ similar)'),

dict(k='Revanesse Ultra + Lido', m='Revanesse · Prollenium', t='dados de plataforma não detalhados no acervo*', c='A',
 comp='128/39/0,31 — o menor G′ da linha Revanesse: integração e correção adaptativa.',
 mp='Correções médias com adaptação',
 ind=[('Sulco nasolabial moderado',2),('Labiomentoniano/marionete',2),('Perioral',3),('Lábios',3)],
 ev=['Estrutura e projeção'],
 esc='Escolha para adaptação em sulcos móveis; para lábio dedicado, o Kiss é mais direcionado.',
 alt='Revanesse Kiss (lábios) · Revanesse Contour+'),

dict(k='Revanesse Kiss Lido', m='Revanesse · Prollenium', t='formulação labial da linha*', c='A',
 comp='131/51/0,39 — G″ proporcionalmente alto: o lábio dinâmico com corpo da Revanesse.',
 mp='Lábio dinâmico com corpo',
 ind=[('Lábios (vermelhão, contorno delicado)',1),('Tubérculos suaves',2),('Perioral',2)],
 ev=['Estrutura','Olheiras'],
 esc='Escolha quando quiser volume labial que se deforma junto com o beijo e a fala.',
 alt='Restylane Kysse (menos dissipativo) · Stylage Special Lips'),

dict(k='Restylane Volyme Lido', m='Restylane · Galderma', t='OBT/XpresHAn*', c='A',
 comp='138/23/0,16 — baixo G′ com forte predominância elástica: volumizador difuso que se integra. Capacidade volumizadora não se prevê pelo G′.',
 mp='Volume difuso com integração',
 ind=[('Bochecha/terço médio (reposição difusa)',1),('Crown lifting',2),('Têmpora volumétrica',2),('Sulco nasolabial (contexto volumétrico)',3),('Marionete',3)],
 ev=['Vértice e projeção focal'],
 esc='Escolha quando quiser VOLUMIZAR E INTEGRAR — a curva suave, não o ponto.',
 alt='Juvéderm Voluma (mais magnitude) · Biogelis Volume'),

dict(k='Revanesse Contour + Lido', m='Revanesse · Prollenium', t='—*', c='A',
 comp='142/39/0,28 — contorno e correção com sustentação moderada.',
 mp='Contorno suave do terço inferior',
 ind=[('Sulco nasolabial',2),('Labiomentoniano/marionete',2),('Pré-jowl',2),('Bochecha/malar moderados',3)],
 ev=['Projeção extrema — o nome "Contour" não significa alto G′'],
 esc='Escolha para desenhar transições com sustentação moderada e adaptação.',
 alt='Revanesse Outline+ (mais elástico) · Saypha Filler'),

dict(k='Saypha Filler Lido', m='Saypha · Croma', t='—*', c='A',
 comp='143/34/0,24 — o degrau de INTEGRAÇÃO da linha Saypha (Filler → Volume → Volume Plus).',
 mp='Correção versátil de sulcos',
 ind=[('Sulco nasolabial',2),('Labiomentoniano',2),('Marionete',2),('Perioral',3),('Têmpora/fronte/supercílio',4)],
 ev=['Estrutura'],
 esc='Escolha para a depressão clássica: preencher com integração e previsibilidade.',
 alt='e.p.t.q S300 (mais corpo) · Sofiderm Derm'),

dict(k='Sofiderm Derm', m='Sofiderm · Aeskins/Techderm', t='MCLPE; AH 20±3 mg/mL; partícula declarada 700 µm*', c='A',
 comp='147/31/0,21 — "preencher o vale sem transformá-lo em vértice". Curioso: G′ MENOR que o Fine Lines (densidade comercial ≠ G′).',
 mp='O vale em tecido móvel',
 ind=[('Sulco nasolabial (vale)',1),('Submalar (transição)',2),('Lóbulo de orelha (indicação comercial)',2),('Lábios (corpo+contorno moderado)',3),('Pré-jowl/marionete',3)],
 ev=['Malar/zigoma em projeção (→ Deep)','Mento e mandíbula','Olheiras','Nariz'],
 esc='Escolha quando a tarefa for PREENCHER o vale — o objetivo é fazer desaparecer a depressão.',
 alt='Revanesse Outline+ (par quase idêntico) · Saypha Filler'),

dict(k='Revanesse Outline+ Lido', m='Revanesse · Prollenium', t='—*', c='A',
 comp='148/33/0,22 — contorno com sustentação: desenha a linha suave do terço inferior.',
 mp='Linhas e transições do terço inferior',
 ind=[('Pré-jowl',2),('Labiomentoniano/marionete',2),('Contorno mandibular leve',3),('Mento moderado',4)],
 ev=['Projeção extrema'],
 esc='Escolha para redesenhar transições que precisam de um pouco mais de firmeza.',
 alt='Sofiderm Derm (par quase idêntico) · Revanesse Shape+ (mais firme)'),

dict(k='Sofiderm Fine Lines', m='Sofiderm · Aeskins/Techderm', t='MCLPE; AH 20±3 mg/mL; partícula declarada 500 µm*', c='A',
 comp='152/37/0,25 — refinamento superficial. Achado do estudo: tem G′ MAIOR que o Derm "média densidade".',
 mp='Microgeometria da superfície',
 ind=[('Linhas periorais',1),('Perioculares estáticas',4),('Lábios (refinamento)',4),('Pés de galinha estáticos',4),('Fronte',4)],
 ev=['Olheiras/calha (SF não medido; 500 µm não é sinônimo de baixo swelling)','Sulco profundo','Volume'],
 esc='Escolha para corrigir a microgeometria — a linha, não o vale.',
 alt='Rennova Fine Lines (mais dinâmico) · Biogelis Fine Lines'),

dict(k='Juvéderm Ultra Plus XC Lido', m='Juvéderm · Allergan', t='Hylacross; AH 24 mg/mL*', c='A',
 comp='161/38/0,24 — "Ultra integra, Ultra Plus sustenta": o degrau de corpo da dupla Hylacross.',
 mp='Sustentação moderada com coesividade',
 ind=[('Sulco nasolabial',2),('Labiomentoniano/marionete',2),('Lábios com corpo',2),('Bochecha/malar',3),('Pré-jowl',3)],
 ev=['Projeção focal extrema'],
 esc='Escolha quando o Ultra XC integraria, mas o defeito pede mais sustentação.',
 alt='Evofill Derm (G′ igual, +50% G″) · Juvéderm Ultra XC'),

dict(k='Evofill Derm', m='Evofill · EVO Pharma', t='MDM FILLER — reticulação DVS; AH 20 mg/mL*', c='A',
 comp='162/57/0,35 — G″ relevante: preenche e adapta COM corpo. Lição da ficha: DVS não significa alto G′.',
 mp='Preencher e adaptar com mais corpo',
 ind=[('Lábios (corpo + adaptação)',1),('Perilabial (preencher sem sobre-estruturar)',2),('Sulcos móveis',2),('Labiomentoniano/marionete (vale)',2),('Têmporas (indicação comercial)',3),('Zigoma como tecido mole',3),('Pré-jowl (vale)',3)],
 ev=['Mento/mandíbula estruturais','Olheiras (SF desconhecido)','Fronte/glabela (risco vascular)'],
 esc='Escolha quando quiser corpo que acompanha: preencher e adaptar, sem virar estrutura.',
 alt='Juvéderm Ultra Plus XC (G′ <1% de diferença) · Belotero Intense'),

dict(k='Neuramis Deep Lido', m='Neuramis · Medytox', t='—*', c='A',
 comp='164/44/0,27 — coesividade percebida + integração + volume moderado; baixa tendência a irregularidades.',
 mp='O lábio nº 1 do autor dentro da linha Neuramis',
 ind=[('Lábios (corpo com regularidade)',1),('Sulco nasolabial',2),('Labiomentoniano',2),('Marionete',2)],
 ev=['Estrutura e projeção'],
 esc='Escolha quando quiser lábio com corpo e segurança de regularidade.',
 alt='Milimetric PRO Intenso (par quase idêntico) · Stylage Special Lips'),

dict(k='Stylage Lips Lido', m='Stylage · Laboratoires VIVACY', t='IPN-Like; AH ≈18,5 mg/g; manitol; lidocaína 0,3%*', c='A',
 comp='167/35/0,21 — formulação dedicada ao lábio: integração, volume suave e contorno natural (🔵🌸 no sistema).',
 mp='Desenhar o lábio preservando o movimento',
 ind=[('Rejuvenescimento labial',2),('Corpo leve/moderado',2),('Contorno e arco do cupido',2),('Linhas periorais',2),('Projeção suave',3),('Colunas filtrais',3),('Tubérculos suaves',3)],
 ev=['Projeção extrema/tubérculo projetado (outro fenótipo)','Hidratação clínica ≠ SF (não medir edema pelo marketing)'],
 esc='Escolha para preencher e desenhar o lábio sem transformá-lo em estrutura focal.',
 alt='Restylane Kysse (mais elástico) · Revanesse Kiss (mais dissipativo)'),

dict(k='Milimetric PRO Intenso Lido', m='Milimetric PRO', t='AH 20 mg/mL + lidocaína*', c='A',
 comp='170/46/0,27 — o topo da linha Milimetric: sustentação e contorno moderados ("alto G′ dentro da marca ≠ alto G′ no mercado").',
 mp='Sustentar dentro da lógica Milimetric',
 ind=[('Mento (fabricante: supraperiosteal)',2),('Pré-jowl',2),('Mandíbula moderada',3),('Malar/bochecha',3),('Sulco nasolabial profundo',3)],
 ev=['Vértice extremo','Olheiras'],
 esc='Escolha quando a linha Milimetric precisar SUSTENTAR — lembrando que 170 Pa é moderado no mapa geral.',
 alt='Neuramis Deep (par quase idêntico) · Rennova Deep Line'),

dict(k='Revanesse Shape + Lido', m='Revanesse · Prollenium', t='—*', c='A',
 comp='173/31/0,18 — maior G′ e menor tan δ da linha Revanesse: o degrau de forma.',
 mp='Sustentação moderada com manutenção de forma',
 ind=[('Mento (corpo)',2),('Mandíbula/pré-jowl',2),('Malar/zigoma',3),('Sulco nasolabial profundo',3)],
 ev=['Projeção máxima (fora da classe)'],
 esc='Escolha quando a Revanesse precisar manter forma — dentro dos limites de um G′ moderado.',
 alt='Rennova Deep Line · Up Deep'),

dict(k='Up Deep Lido', m='UP · Ilikia', t='—*', c='A', fl=['verif'],
 comp='173/32/0,18 — G′ moderado com predominância elástica; o sustentador de vales da linha UP.',
 mp='Sustentar o vale',
 ind=[('Sulco nasolabial',2),('Labiomentoniano',2),('Marionete',2),('Pré-jowl',2)],
 ev=['Vértice','Lábios (há opções mais dinâmicas)'],
 esc='Escolha quando o vale precisar de correção que permaneça.',
 alt='Revanesse Shape+ · Rennova Deep Line'),

dict(k='Biogelis Fine lines', m='Biogelis', t='—*', c='A',
 comp='177/35/0,20 — linhas superficiais com um pouco mais de corpo (no teto do território azul).',
 mp='Terço superior superficial',
 ind=[('Fronte',2),('Supercílio',2),('Têmpora superficial',3),('Glabela (alerta vascular)',4)],
 ev=['Estrutura','Olheiras automáticas'],
 esc='Escolha para espalhar no terço superior quando quiser um pouco mais de presença que os ultraleves.',
 alt='Sofiderm Fine Lines · Restylane Refyne (bem mais leve)'),

dict(k='Biogelis Global Lido', m='Biogelis', t='—*', c='A',
 comp='177/34/0,19 — o coringa da linha: integração, versatilidade e suporte moderado.',
 mp='Correções médias versáteis',
 ind=[('Sulco nasolabial',2),('Labiomentoniano/marionete',2),('Perioral',3),('Bochecha/têmpora intermediárias',3)],
 ev=['Projeção'],
 esc='Escolha como ferramenta ampla de correções médias com integração.',
 alt='Sofiderm Derm · Saypha Filler'),

dict(k='Restylane Kysse Lido', m='Restylane · Galderma', t='OBT/XpresHAn*', c='A',
 comp='179/25/0,14 — o contraexemplo labial: baixo G′ E baixo tan δ. Forma que dura sem rigidez percebida.',
 mp='Lábio com forma persistente e movimento natural',
 ind=[('Lábios (volume + contorno + kissability)',1),('Arco do cupido',2),('Perioral',3)],
 ev=['Arquitetura labial extrema (→ Rennova Lips Plus)'],
 esc='Escolha quando quiser que a forma do lábio permaneça entre as mímicas — sem parecer duro.',
 alt='Stylage Special Lips (mais dissipativo) · Juvéderm Volbella (precisão elástica)'),

dict(k='Rennova Deep Line Lido', m='Rennova', t='AH 23 mg/mL*', c='A',
 comp='183/32/0,17 — a ferramenta de SULCO da linha Rennova: vale com sustentação.',
 mp='Sulcos bem marcados',
 ind=[('Sulco nasolabial (indicação oficial)',1),('Marionete (indicação oficial)',1),('Labiomentoniano',2),('Pré-jowl (vale)',2)],
 ev=['Vértice e projeção'],
 esc='Escolha quando o defeito for um SULCO: Deep Line preenche e segura.',
 alt='Rennova Lift (continuidade) · Stylage L (vale profundo)'),

dict(k='Belotero Intense Lido', m='Belotero · Merz', t='CPM*', c='A',
 comp='186/61/0,33 — o 2º fenótipo labial: dinâmico com CORPO (G″ 61 Pa, o traço "amarelo" do grupo).',
 mp='Lábio com corpo e integração CPM',
 ind=[('Lábios (volume moderado + definição)',1),('Sulco nasolabial',2),('Marionete',3),('Labiomentoniano',3)],
 ev=['Olheiras (não priorizar)','Projeção máxima'],
 esc='Escolha quando o lábio pedir corpo E integração — mais presença que o Balance, mesma família CPM.',
 alt='Evofill Ultra Deep (assinatura próxima) · Revanesse Kiss'),

dict(k='Evofill Ultra Deep', m='Evofill · EVO Pharma', t='MDM FILLER — DVS; AH 20 mg/mL; "alta viscosidade" comercial*', c='A',
 comp='200/57/0,29 — sustentação com adaptabilidade; fica 0,33 Pa abaixo do corte dos intermediários. "Ultra Deep" não é G′ extremo: nome ≠ reologia.',
 mp='Sustentar mais, sem estrutura extrema',
 ind=[('Malar profundo (corpo/suporte)',2),('Pré-jowl (vale+suporte)',2),('Zigomático profundo',3),('Mento (corpo)',3),('Contorno mandibular (continuidade)',3),('Têmpora profunda',4),('Sulco nasolabial com sustentação',3)],
 ev=['Lábios (→ Derm)','Olheiras','Fronte/glabela','Nariz'],
 esc='Escolha quando o Derm adaptaria, mas o defeito pede mais suporte.',
 alt='Belotero Intense (assinatura próxima) · Sofiderm Deep'),

# ---------------- FAMÍLIA AMARELA 🟡 — PREENCHEDOR (14) ----------------
dict(k='Rennova Ultra Volume Lido', m='Rennova', t='AH 23 mg/mL; categoria oficial VOLUMIZAÇÃO*', c='M',
 comp='222/32/0,15 — o volumizador da linha NÃO é o maior G′ dela: convexidade, não vértice. "G′ não é volumização."',
 mp='Reconstruir a convexidade (CURVA)',
 ind=[('Bochecha (convexidade)',1),('Malar volumétrico',1),('Compartimentos do terço médio',2),('Têmpora',4),('Pré-jowl amplo',4),('Mento (corpo)',4),('Marionete volumétrica',4)],
 ev=['Lábios (apesar do nome da linha)','Olheiras ("alta expansão" comercial pede cautela)','Vértice (→ Lift Plus)'],
 esc='Escolha quando a tarefa for CONVEXIDADE: Ultra Volume volumiza; Lift Plus projeta.',
 alt='Sofiderm Deep · Juvéderm Voluma'),

dict(k='Sofiderm Deep', m='Sofiderm · Aeskins/Techderm', t='MCLPE; AH 20±3 mg/mL; partícula declarada 1000 µm; duração comercial "até 24 meses"*', c='M',
 comp='223/43/0,19 — o salto estrutural da linha facial Sofiderm: mais suporte SEM entrar no extremo da projeção.',
 mp='Curva + suporte (não vértice)',
 ind=[('Malar (volume/suporte)',2),('Mento (corpo/sustentação)',2),('Mandíbula (continuidade + corpo)',2),('Pré-jowl (vale + suporte)',2),('Têmporas (indicação comercial)',3),('Fossa piriforme (alerta vascular)',3),('Bochecha profunda',3)],
 ev=['Vértice extremo','Sulco nasolabial direto (→ Derm)','Lábios','Olheiras (G′ moderado ≠ baixo swelling)','Fronte/glabela','Nariz'],
 esc='Escolha para construir curvas e pontos de suporte — não para transformar todo depósito em vértice.',
 alt='e.p.t.q S300 (mesmo G′, +25% G″) · Rennova Ultra Volume'),

dict(k='e.p.t.q S 300 Lido', m='e.p.t.q · Jetema', t='AH 24 mg/mL*', c='M',
 comp='226/53/0,23 — o degrau do meio da linha: integração + suporte moderado. Concordância notável com a literatura (0,1 Hz: 174 vs 173 Pa).',
 mp='Corpo com adaptação',
 ind=[('Sulco nasolabial',2),('Labiomentoniano',2),('Marionete',2),('Bochecha moderada',3)],
 ev=['Projeção máxima','Olheiras (24 mg/mL)'],
 esc='Escolha quando quiser preencher com corpo sem abrir mão da adaptação.',
 alt='Sofiderm Deep (par de G′) · Belotero Volume+'),

dict(k='Biogelis Volume Lido', m='Biogelis', t='coesividade declarada pela marca*', c='M',
 comp='252/49/0,19 — preencher e manter volume com gel íntegro (classe 🟢 do pilar coesividade+volumização).',
 mp='Preencher e manter volume',
 ind=[('Sulco nasolabial',1),('Labiomentoniano',2),('Marionete',2),('Crown lifting',2),('Bochecha',2),('Têmpora',3)],
 ev=['Vértice extremo'],
 esc='Escolha para reposição volumétrica integrada: o gel permanece como massa.',
 alt='Belotero Volume+ (mais dissipativo) · Saypha Volume (mais elástico)'),

dict(k='Saypha Volume Lido', m='Saypha · Croma', t='—*', c='M',
 comp='252/29/0,12 — sustentação elástica limpa em volume médio (tan δ baixíssimo para a faixa).',
 mp='Sustentação limpa em volume médio',
 ind=[('Bochecha',2),('Malar',2),('Fossa piriforme (alerta vascular)',2),('Crown lifting',3),('Mento/mandíbula',4)],
 ev=['Lábios (tan δ 0,12)','Olheiras'],
 esc='Escolha quando quiser volume que mantém forma com o mínimo de dissipação.',
 alt='Rennova Lift (par próximo) · Juvéderm Volbella'),

dict(k='Juvéderm Volbella Lido', m='Juvéderm · Allergan', t='Vycross; AH 15 mg/mL*', c='M',
 comp='253/40/0,16 — a prova de que concentração ≠ G′: 15 mg/mL com mais G′ que os Hylacross de 24. Precisão elástica.',
 mp='Desenhar com precisão o que deve permanecer',
 ind=[('Contorno labial (definição, tubérculos)',1),('Perioral (estudo de 12 meses)',2),('Vermelhão controlado',2),('Lábio (corpo moderado)',3)],
 ev=['Volume labial máximo','Regiões que pedem alta dissipação'],
 esc='Escolha quando o lábio pedir DESENHO: precisão e permanência, com delicadeza clínica.',
 alt='Restylane Kysse (mais leve) · Rennova Lips Plus (arquitetural)'),

dict(k='Belotero Volume + Lido', m='Belotero · Merz', t='CPM*', c='M', fl=['verif'],
 comp='253/57/0,23 — volumizador CPM com dissipação alta para a faixa: volume que se integra. (Dados idênticos ao Neauvia Intense no laudo — em re-verificação.)',
 mp='Volumizar com integração CPM',
 ind=[('Têmporas',1),('Malar/bochecha',2),('Crown lifting',2),('Sulco nasolabial',4),('Labiomentoniano',4),('Mento/mandíbula (volumizar, não estruturar)',4)],
 ev=['Olheiras (não priorizar)','Vértice extremo'],
 esc='Escolha para volumizar com naturalidade CPM — capacidade volumizadora não se prevê só pelo G′.',
 alt='Biogelis Volume · Stylage L'),

dict(k='Neauvia Intense', m='Neauvia · Matex Lab', t='plataforma não documentada no acervo*', c='M', fl=['verif','pend'],
 comp='253/57/0,23 — valores IDÊNTICOS ao Belotero Volume+ no laudo (provável duplicação de linha; re-verificar com o laboratório antes de uso clínico do dado).',
 mp='— monografia pendente —',
 ind=[('Candidato da família amarela: vale/corpo/curva (a confirmar após re-verificação)',4)],
 ev=['Usar o dado atual como definitivo'],
 esc='Ficha aguardando dado re-verificado e monografia do autor.',
 alt='Belotero Volume+ · Biogelis Volume'),

dict(k='Rennova Lift', m='Rennova', t='AH 23 mg/mL (linha atual "Lift Lido")*', c='M',
 comp='254/29/0,11 — G′ intermediário com tan δ muito baixo: SUSTENTAR e preservar a correção.',
 mp='Manutenção da correção',
 ind=[('Sulco nasolabial (indicação oficial)',1),('Labiomentoniano',2),('Pré-jowl (continuidade)',2),('Malar (suporte)',3)],
 ev=['Lábios','Regiões que pedem dissipação (tan δ 0,11 é quase "mola pura")'],
 esc='Escolha quando quiser que o vale corrigido continue corrigido: predominância elástica.',
 alt='Saypha Volume (par) · Stylage L'),

dict(k='Stylage L Lido', m='Stylage · VIVACY', t='IPN-Like; AH 24 mg/g; manitol; monofásico (literatura)*', c='M', fl=['ifu'],
 comp='260/42/0,16 — o centro estrutural da família Stylage. "O amarelo é a cor do vale."',
 mp='O vale profundo com suporte',
 ind=[('Sulco nasolabial (RCT NICE: não inferior a Juvéderm Ultra 3 em 12 meses; RCT chinês ~390 pts vs Restylane)',1),('Marionete profunda',2),('Labiomentoniano profundo',2),('Submalar/bochecha (concavidade)',2),('Pré-jowl (vale)',2),('Dorso das mãos (indicação comercial)',3)],
 ev=['IFU CONTRAINDICA: lábios, periorbital, olheiras, pés de galinha, fronte, glabela','Nariz (posicionamento comercial existe; alto risco vascular)'],
 esc='Escolha para preencher o vale com suporte, sem transformar a correção em vértice.',
 alt='Cutegel CL-Max · Biogelis Volume'),

dict(k='Cutegel Lidocaine CL-Max', m='Cutegel · JDBIO', t='BDDE "3D cross-linked"; AH 20 mg/mL; 1,1 mL*', c='M',
 comp='282/57/0,20 — preencher + sustentar + modelar; na fronteira dos "equilibrados" (tan δ 0,20). Suporte clínico forte no SNL.',
 mp='O sulco nasolabial com evidência',
 ind=[('Sulco nasolabial (NMPA 2025; RCT 340 pts vs Restylane: não inferior em WSRS na semana 24)',1),('Bochecha (volume + sustentação)',2),('Malar volumétrico',2),('Marionete',3),('Labiomentoniano',3),('Pré-jowl (vale + suporte)',3),('Mento (corpo)',4),('Têmpora',4)],
 ev=['Mento em projeção máxima','Nariz','Ângulo (vértice extremo)','Fronte','Lábios (CL-S/CL-N na linha)','Olheiras'],
 esc='Escolha para preencher e modelar com sustentação — sem transformar todo volume em vértice.',
 alt='Hyafilia Soft (par quase idêntico) · Neauvia Stimulate (G′ igual, +37% G″)'),

dict(k='Hyafilia S Plus Lido', m='Hyafilia Soft · CHA Meditech', t='CHA-HEART; AH 20 mg/mL; granulometria declarada 240 µm; derme superficial (fabricante)*', c='M',
 comp='284/59/0,21 — "SOFT NÃO É AZUL": o mais leve da linha Hyafilia ainda é um intermediário alto no mapa geral.',
 mp='Refinar e preencher com a menor estrutura DA LINHA',
 ind=[('Linhas periorais',2),('Contorno labial delicado',2),('Sulco nasolabial leve/moderado',2),('Marionete/labiomentoniano leve',3),('Corpo labial moderado',3)],
 ev=['Olheiras (não escolher pelo nome; SF não medido)','Periorbital (reologicamente seletivo em pele fina)','Glabela (risco vascular)','Projeção (→ Mold/Volume)'],
 esc='Escolha o degrau delicado da Hyafilia lembrando: 284 Pa não é um gel de baixo G′ no mercado.',
 alt='Cutegel CL-Max (assinatura quase sobreponível) · e.p.t.q S300'),

dict(k='Neauvia Stimulate', m='Neauvia · Matex Lab', t='plataforma não documentada no acervo*', c='M', fl=['verif','pend'],
 comp='286/78/0,27 — valores IDÊNTICOS ao Singderm no laudo (provável duplicação; re-verificar).',
 mp='— monografia pendente —',
 ind=[('Candidato amarelo com dissipação alta (a confirmar após re-verificação)',4)],
 ev=['Usar o dado atual como definitivo'],
 esc='Ficha aguardando dado re-verificado e monografia do autor.',
 alt='Singderm · Cutegel CL-Max'),

dict(k='Singderm Lido', m='Singderm · Singclean', t='SingLink — reticulação DVS; AH 24 mg/mL; DVS residual "não detectado" (espec. ≤2 µg/g)*', c='M', fl=['verif'],
 comp='286/78/0,27 — sustentação que acompanha: o maior G″ proporcional da família amarela. (Valores idênticos ao Neauvia Stimulate no laudo — em re-verificação.)',
 mp='Sustentação moderada com adaptação',
 ind=[('Sulco nasolabial',1),('Labiomentoniano',2),('Marionete',2),('Perioral',3),('Lábios',4),('Bochecha',4)],
 ev=['Projeção extrema'],
 esc='Escolha quando o vale pedir sustentação que ainda acompanha o movimento.',
 alt='Cutegel CL-Max (G′ igual, bem menos dissipativo) · Belotero Volume+'),

# ---------------- FAMÍLIA ROXA 🟣 — ESTRUTURAL (18) ----------------
dict(k='Restylane Defyne Lido', m='Restylane · Galderma', t='OBT/XpresHAn*', c='R',
 comp='293/24/0,08 — caso de borda do mapa (roxo com G′ <300): a maior predominância elástica da categoria "flexível".',
 mp='Suporte que se mantém no movimento',
 ind=[('Sulco nasolabial profundo',1),('Labiomentoniano',2),('Marionete',2),('Bochecha/malar',3),('Mento (corpo)',3)],
 ev=['Planos superficiais em pele fina','Regiões que pedem dissipação'],
 esc='Escolha quando a correção precisar sobreviver à mímica: tan δ 0,08 com G′ moderado-alto.',
 alt='Juvéderm Volift (mais magnitude) · Rennova Lift'),

dict(k='Stylage XL Lido', m='Stylage · VIVACY', t='IPN-Like; AH 26 mg/g; manitol; monofásico (estudo Beauty Volume)*', c='R',
 comp='305/47/0,15 — "roxo de entrada": estrutural, mas não extremo. Volume + sustentação + contorno.',
 mp='Restaurar a curva e sustentar',
 ind=[('Malar (Beauty Volume, 40 pts: melhora mantida 6→18 meses)',1),('Bochecha (restauração volumétrica)',2),('Zigoma (curva)',2),('Têmporas (29/40 tratadas no estudo)',2),('Mento (corpo + projeção moderada)',2),('Mandíbula/oval (continuidade)',2),('Pré-jowl (vale + estrutura)',3)],
 ev=['Sulco nasolabial direto (→ L)','Marionete superficial móvel','Lábios (→ linha labial)','Olheiras (alto G′ ≠ baixo SF)','Fronte/glabela','Nariz'],
 esc='Escolha para restaurar curva e sustentar volume sem depender de estrutura extrema.',
 alt='UP Contour e Yvoire Classic+ (quase o mesmo espaço reológico) · Juvéderm Voluma'),

dict(k='Neuramis Volume', m='Neuramis · Medytox', t='—*', c='R',
 comp='314/48/0,15 — o degrau ESTRUTURAR da linha Neuramis.',
 mp='Estrutura na lógica Neuramis',
 ind=[('Mento',1),('Mandíbula',2),('Ângulo mandibular',2),('Arco zigomático',2),('Fossa piriforme (alerta vascular)',2)],
 ev=['Lábios','Fronte/glabela','Olheiras'],
 esc='Escolha quando a linha Neuramis precisar construir e manter forma.',
 alt='Stylage XL · UP Contour'),

dict(k='Yvoire Classic+ Lido', m='Yvoire · LG Chem', t='bifásico; AH 22 mg/mL*', c='R',
 comp='320/46/0,14 — SUSTENTAR: preencher com manutenção de forma (o abridor da linha Yvoire).',
 mp='Preencher e sustentar',
 ind=[('Sulco nasolabial profundo',2),('Labiomentoniano',2),('Marionete',2),('Malar moderado',3)],
 ev=['Dinâmica alta superficial'],
 esc='Escolha quando o vale profundo pedir correção que permaneça.',
 alt='Stylage XL / UP Contour (assinaturas quase iguais) · Perfectha Deep'),

dict(k='Up Contour Lido', m='UP · Ilikia', t='—*', c='R',
 comp='328/48/0,15 — estrutura + contorno + definição; citado também na classe complementar de baixo SF.',
 mp='Definir contorno com precisão',
 ind=[('Mento',2),('Mandíbula',2),('Ângulo mandibular',2),('Arco zigomático',2),('Malar (projeção focal)',3),('Olheira (classe SF complementar — SF não medido)',4),('Nariz (risco vascular)',4)],
 ev=['Superficial dinâmico'],
 esc='Escolha para desenhar contorno em plano profundo/supraperiostal.',
 alt='Stylage XL / Yvoire Classic+ (par) · UP Max (mais dissipativo)'),

dict(k='Sofiderm Derm Sub-Skin', m='Sofiderm · Aeskins/Techderm', t='MCLPE; AH 20±3 mg/mL; partícula declarada 1800 µm; linha corporal*', c='R', fl=['pend'],
 comp='331/47/0,14 — o estrutural corporal da Sofiderm: volumizar + sustentar + manter estrutura no corpo.',
 mp='Estrutura e projeção corporal',
 ind=[('Glúteos (grande projeção)',1),('Hip dips volumosos',1),('Contorno corporal estrutural',2),('Coxas (estrutura)',2)],
 ev=['Irregularidades finas (→ Derm Plus)','Uso facial (produto corporal)'],
 esc='Escolha quando o corpo pedir volume COM estrutura: a dupla corporal não tem uma única reologia.',
 alt='Sofiderm Derm Plus (o adaptativo da dupla)'),

dict(k='Finahfil Intense', m='Finahfil', t='dados de plataforma não documentados no acervo*', c='R', fl=['pend'],
 comp='339/38/0,11 — assinatura fortemente elástica em magnitude moderada-alta; sem monografia do autor até o momento.',
 mp='— monografia pendente —',
 ind=[('Candidato estrutural: mento/mandíbula/zigoma (a confirmar na monografia)',4)],
 ev=['Atribuir indicações antes da monografia'],
 esc='Ficha aguardando a monografia do autor; números do laudo já validados.',
 alt='Neuramis Volume · Sofiderm Sub-Skin'),

dict(k='Juvéderm Volift Lido', m='Juvéderm · Allergan', t='Vycross; AH 17,5 mg/mL*', c='R', fl=['verif'],
 comp='363/32/0,09 — sustentação com tan δ baixíssimo. (Laudo registra valores IDÊNTICOS ao Voluma em lotes distintos — em re-verificação.)',
 mp='Manutenção elástica em movimento',
 ind=[('Sulco nasolabial profundo',1),('Malar/bochecha',2),('Pré-jowl',2),('Mandíbula',3),('Zigoma',3),('Mento moderado',3)],
 ev=['Superficial fino'],
 esc='Escolha quando o vale profundo estiver em território móvel e a correção precisar durar.',
 alt='Restylane Defyne (menos magnitude) · Juvéderm Voluma'),

dict(k='Juvéderm Voluma Lido', m='Juvéderm · Allergan', t='Vycross; AH 20 mg/mL*', c='R', fl=['verif'],
 comp='363/32/0,09 — "VOLUMA CONSTRÓI CONVEXIDADE": o volumizador-sustentador de referência. (Dados idênticos ao Volift no laudo — em re-verificação.)',
 mp='Volumizar e sustentar convexidades',
 ind=[('Malar',1),('Bochecha (convexidade)',1),('Têmporas',2),('Zigoma',2),('Pré-jowl',3),('Mento moderado',3),('Olheira (citado na classe SF — projeção com precisão; SF não medido)',4)],
 ev=['Lábios','Planos superficiais'],
 esc='Escolha quando a tarefa for a CURVA que se mantém: convexidade, não vértice.',
 alt='Juvéderm Volux (o vértice) · Stylage XL'),

dict(k='Perfectha Deep', m='Perfectha · Sinclair', t='bifásico*', c='R',
 comp='386/47/0,12 — preencher + sustentar vales profundos. Curiosidade do estudo: o Derm mediu G′ MAIOR que o Deep (inversão da escada comercial).',
 mp='Sustentação de vales profundos',
 ind=[('Sulco nasolabial profundo',2),('Labiomentoniano',2),('Marionete',2),('Pré-jowl',2),('Bochecha moderada',3)],
 ev=['Superficial dinâmico'],
 esc='Escolha para o vale profundo que precisa de suporte real.',
 alt='Perfectha Derm (mediu acima) · Juvéderm Volift'),

dict(k='Rennova Lips Plus Lido', m='Rennova', t='Lips Collection; AH 24 mg/mL; 1,1 mL; Anvisa 80117580874*', c='R',
 comp='402/72/0,18 — a prova de que lábio pode exigir G′ alto: 2º maior G′ e MAIOR G″ da família Rennova. Arquitetura labial.',
 mp='Construir a ARQUITETURA do lábio',
 ind=[('Volume labial estrutural (indicação oficial)',1),('Contorno labial (oficial)',1),('Arco do cupido (oficial)',1),('Projeção labial',2),('Tubérculos definidos',2),('Vermelhão (corpo)',2)],
 ev=['Linhas periorais superficiais (→ Fine Lines)','SNL/marionete','Mento/mandíbula/zigoma (→ Lift Plus)','Olheiras','Refinamento discreto'],
 esc='Escolha quando o projeto labial for corpo + contorno + projeção — construir sem esquecer que o lábio se move.',
 alt='Juvéderm Volbella (precisão elástica) · Restylane Kysse (forma sem rigidez)'),

dict(k='Perfectha Derm', m='Perfectha · Sinclair', t='bifásico*', c='R',
 comp='441/50/0,11 — o MAIOR G′ da família Perfectha no estudo, apesar do rótulo "Derm" (nome ≠ reologia; posicionamento comercial é de integração).',
 mp='Sustentação acima do que o rótulo sugere',
 ind=[('Sulcos moderados (posicionamento comercial)',2),('Marionete',2),('Labiomentoniano',3),('Perioral',4)],
 ev=['Confiar na escada comercial: no ensaio, Derm > Deep','Planos superficiais finos dado o G′ medido'],
 esc='Escolha com consciência da inversão: no nosso protocolo este gel sustenta mais do que o nome sugere.',
 alt='Perfectha Deep · Rennova Lift Plus'),

dict(k='Rennova Lift Plus Lido', m='Rennova', t='AH 24–25 mg/mL (divergência entre fontes oficiais — conferir IFU)*', c='R',
 comp='476/34/0,07 — o extremo estrutural da Rennova: G′ alto com a menor dissipação (tan δ 0,07). GEOMETRIA.',
 mp='Construir o vértice e preservar a geometria',
 ind=[('Mento (vértice/projeção)',1),('Mandíbula (linha)',1),('Ângulo mandibular (vértice)',1),('Zigoma (projeção focal/ponto de luz)',1),('Malar estrutural',2),('Pré-jowl (reconstrução da linha)',2),('Bochecha (pontos estruturais)',4),('Têmporas',4),('Marionete (estratégia estrutural)',4)],
 ev=['Sulco nasolabial direto','Lábios (→ Lips Plus)','Olheiras (→ Eyes Lines)','Nariz: mecanicamente coerente, MAS "G′ alto não torna o nariz seguro"'],
 esc='Escolha quando a geometria importar mais que o volume: construir o ponto, não ocupar o espaço.',
 alt='Saypha Volume Plus (praticamente sobreposto) · Juvéderm Volux'),

dict(k='Saypha Volume Plus Lido', m='Saypha · Croma', t='—*', c='R',
 comp='489/36/0,07 — estrutura elástica máxima da Saypha; par quase idêntico do Rennova Lift Plus (diferenças <3%).',
 mp='Estrutura e projeção',
 ind=[('Mento',1),('Mandíbula',1),('Ângulo mandibular',2),('Zigoma',2),('Malar projetivo',2),('Fossa piriforme (alerta vascular)',2),('Nariz (ressalva de risco)',4)],
 ev=['Lábios','Dinâmica superficial','Olheiras'],
 esc='Escolha para o degrau final da escada Saypha: INTEGRAÇÃO → SUSTENTAÇÃO → ESTRUTURA.',
 alt='Rennova Lift Plus (par) · Juvéderm Volux'),

dict(k='Yvoire Contour+ Lido', m='Yvoire · LG Chem', t='bifásico; AH ~22 mg/mL; partícula grande declarada*', c='R',
 comp='580/61/0,10 — o produto-símbolo da classe BAIXO SF: projeção com PRECISÃO volumétrica ("quero saber quanto volume coloco e quanto permanece").',
 mp='Olheiras: projeção com precisão e baixa expansão',
 ind=[('Olheiras (1ª escolha do autor; plano subcutâneo superficial na técnica dele)',1),('Transição palpebromalar',1),('Mento (projeção)',2),('Mandíbula',2),('Zigoma',2),('Nariz (risco vascular)',4)],
 ev=['Escolher olheira pelo G′ — aqui quem manda é o comportamento hídrico','Dinâmica alta superficial'],
 esc='Escolha na olheira quando não quiser depender de absorção de água para gerar resultado.',
 alt='Perfectha Subskin (mesma classe SF) · Restylane Lyft'),

dict(k='Juvéderm Volux', m='Juvéderm · Allergan', t='Vycross; AH 25 mg/mL*', c='R', fl=['ifu'],
 comp='669/49/0,07 — o menor tan δ do banco: máxima predominância elástica prática. "VOLUX CONSTRÓI VÉRTICE."',
 mp='Projetar e definir onde a geometria importa',
 ind=[('Mento (vértice)',1),('Mandíbula (definição — indicação oficial)',1),('Ângulo mandibular',1),('Zigoma',2),('Pré-jowl (linha)',2),('Malar',4)],
 ev=['IFU CONTRAINDICA: lábios, periorbital, glabela','Nariz (racional existe; risco vascular)','Qualquer tarefa de integração'],
 esc='Escolha quando o projeto for o PONTO: vértice definido que permanece.',
 alt='Rennova Lift Plus (menos magnitude) · Restylane Shaype (mais)'),

dict(k='Hyafilia V Plus Lido', m='Hyafilia Volume · CHA Meditech', t='CHA-HEART; AH 20 mg/mL; granulometria declarada 840 µm*', c='R',
 comp='841/123/0,15 — o 2º maior G′ do banco e um dos 2 únicos "roxo completo". Mesmos 20 mg/mL do Soft, com quase 3× a magnitude: concentração ≠ mecânica.',
 mp='Projetar e estruturar com a maior magnitude da linha',
 ind=[('Mento (corpo, projeção, alongamento, vértice)',1),('Mandíbula (linha/ângulo/definição)',1),('Arco zigomático',1),('Malar (vértice)',2),('Contorno facial',2),('Pré-jowl (estrutura)',2),('Fossa piriforme (alerta vascular)',2),('Grandes deficiências de suporte',2),('Têmporas (curva integrada)',4),('SNL muito profundo (suporte)',4),('Nariz (seletivo — IFU e treinamento)',4)],
 ev=['Lábios','Olheiras (indicação comercial existe, mas NÃO priorizar sem SF medido)','Fronte/glabela','Linhas finas e adaptação dinâmica'],
 esc='Escolha quando a tarefa exigir a maior magnitude elástica da família: MOLD modela; VOLUME projeta.',
 alt='Restylane Shaype (mesmo tan δ, teto do banco) · Juvéderm Volux'),

dict(k='Restylane Shaype Lido', m='Restylane · Galderma', t='NASHA HD; AH 25 mg/mL; conceito bone-mimicking*', c='R',
 comp='936/142/0,15 — o teto estrutural do banco (28× o G′ do Balance) e o outro "roxo completo". Construção sobre o osso.',
 mp='Bone-mimicking: construir sobre o osso',
 ind=[('Mento (indicação oficial; supraperiostal)',1),('Mandíbula',2),('Ângulo mandibular',2),('Zigoma',2),('Nariz (racional reológico; uso seletivo — risco vascular)',4)],
 ev=['Todo plano superficial/dinâmico','Lábios','Olheiras','Separar sempre racional reológico de indicação regulatória'],
 esc='Escolha quando o projeto for esqueleto: máxima estrutura, geometria óssea.',
 alt='Hyafilia V Plus · Juvéderm Volux · Restylane Lyft'),

# ---------------- FAMÍLIA ROXO+VERDE 🟣🟢 — ESTRUTURAL MALEÁVEL (10) ----------------
dict(k='Perfectha Subskin', m='Perfectha · Sinclair', t='bifásico*', c='RV', fl=['verif'],
 comp='343/52/0,15 — classe BAIXO SF: precisão + projeção + baixa expansão. (tan δ impresso no laudo como 0,20; recalculado = 0,15 — errata solicitada.)',
 mp='Precisão volumétrica infraorbitária',
 ind=[('Olheiras (1ª escolha da classe SF)',1),('Projeção com precisão',2),('Mento/zigoma (projeção moderada)',3)],
 ev=['Escolher olheira pelo G′','Superficial dinâmico'],
 esc='Escolha na olheira quando quiser previsibilidade volumétrica com estrutura maleável.',
 alt='Yvoire Contour+ (classe SF) · Restylane Lyft'),

dict(k='Up Max Lido', m='UP · Ilikia', t='—*', c='RV', fl=['verif'],
 comp='351/72/0,21 — estrutura QUE VOLUMIZA: G″ 51% maior que o UP Contour. O braço "cheio" da dupla estrutural UP.',
 mp='Estruturar e volumizar ao mesmo tempo',
 ind=[('Malar/zigoma',2),('Bochecha (volume com suporte)',2),('Mento (corpo)',2),('Mandíbula/pré-jowl',2)],
 ev=['Linhas finas','Olheiras'],
 esc='Escolha quando quiser estrutura com corpo — o Contour define, o Max preenche estruturando.',
 alt='UP Contour (menos dissipativo) · e.p.t.q S500'),

dict(k='e.p.t.q S 500 Lido', m='e.p.t.q · Jetema', t='AH 24 mg/mL*', c='RV',
 comp='355/67/0,19 — o degrau estrutural da linha e.p.t.q, com dissipação relevante: estrutura modelável.',
 mp='Estrutura e projeção na lógica e.p.t.q',
 ind=[('Mento',1),('Arco zigomático',1),('Mandíbula',2),('Ângulo mandibular',2),('Fossa piriforme (alerta vascular)',2)],
 ev=['Lábios','Fronte','Olheiras (24 mg/mL)','Nariz (ressalva)'],
 esc='Escolha para estruturar com um gel que ainda aceita modelagem.',
 alt='Biogelis Volumax (par) · Yvoire Volume+'),

dict(k='Yvoire Volume+ Lido', m='Yvoire · LG Chem', t='bifásico; AH 22 mg/mL*', c='RV', fl=['verif'],
 comp='359/56/0,16 — ESTRUTURAR: o volumizador estrutural bifásico da Yvoire. (Sem lote na Tabela 1 do laudo — errata solicitada.)',
 mp='Estrutura com corpo bifásico',
 ind=[('Mento',2),('Mandíbula',2),('Zigoma',2),('Malar estrutural',3)],
 ev=['Dinâmico superficial'],
 esc='Escolha o meio da escada Yvoire: CLASSIC sustenta → VOLUME estrutura → CONTOUR corrige com precisão.',
 alt='e.p.t.q S500 · Biogelis Volumax'),

dict(k='Biogelis Volumax Lido', m='Biogelis', t='—*', c='RV',
 comp='386/72/0,19 — o estrutural da Biogelis, com G″ alto: estrutura que preenche.',
 mp='Estruturar na lógica Biogelis',
 ind=[('Mento',1),('Mandíbula',1),('Zigoma',2),('Fossa piriforme (alerta vascular)',2),('Nariz (ressalva de risco)',4)],
 ev=['Lábios','Fronte','Olheiras'],
 esc='Escolha o degrau final da escada Biogelis: ESPALHAR → INTEGRAR → VOLUMIZAR → ESTRUTURAR.',
 alt='e.p.t.q S500 (par) · UP Max'),

dict(k='Hyafilia M Plus Lido', m='Hyafilia Mold · CHA Meditech', t='CHA-HEART; AH 20 mg/mL; granulometria declarada 380 µm*', c='RV',
 comp='526/83/0,16 — o ponto em que a Hyafilia deixa de preencher e passa a MODELAR: estrutura intermediária entre Soft e Volume.',
 mp='Modelagem estrutural (curva estruturada)',
 ind=[('Mento (corpo, projeção moderada, assimetrias)',1),('Mandíbula (continuidade/definição — "uma das aplicações mais intuitivas")',1),('Modelagem malar (curva estruturada)',1),('Zigoma (estrutura sem extremo)',2),('Pré-jowl (vale + linha)',2),('Sulco nasolabial PROFUNDO (vale + suporte)',2),('Marionete profunda',3),('Fossa piriforme (alerta vascular)',3),('Têmporas',4)],
 ev=['Olheiras (indicação comercial presente; NÃO priorizar sem SF)','Volume labial difuso (contorno = seletivo)','Nariz','Fronte/glabela','Vértice máximo (→ Volume)'],
 esc='Escolha quando quiser modelar e sustentar sem a magnitude máxima: MOLD = mento modelado; VOLUME = mento projetado.',
 alt='Restylane Lyft (modelável de maior magnitude) · Perfectha Derm'),

dict(k='Restylane Skinbooster Lido', m='Restylane · Galderma', t='NASHA (linha Vital)*', c='RV', fl=['pend','verif'],
 comp='563/148/0,26 — assinatura surpreendente para um "skinbooster": G′ 563 Pa com G″ altíssimo. Mais um lembrete de que NOME ≠ REOLOGIA; dado prioritário para re-verificação e monografia.',
 mp='— monografia pendente —',
 ind=[('Aguardando monografia e re-verificação do dado (assinatura atípica para a categoria)',4)],
 ev=['Assumir comportamento de skinbooster leve a partir do nome'],
 esc='Ficha aguardando monografia; use o caso como aula: o nome comercial não prevê a assinatura.',
 alt='Restylane Lido (dissipação alta semelhante)'),

dict(k='Restylane Lido (lote 22647)', m='Restylane · Galderma', t='NASHA; o clássico (1996/2003)*', c='RV',
 comp='618/162/0,26 — alto G′ com o G″ mais alto do banco em proporção: estrutura com equilíbrio viscoelástico ("modelável").',
 mp='O clássico NASHA: estrutura que aceita modelagem',
 ind=[('Sulco nasolabial profundo',2),('Labiomentoniano',2),('Marionete',2),('Usos estruturais gerais',4),('Mento/mandíbula',4)],
 ev=['Planos superficiais finos','Regiões de integração delicada'],
 esc='Escolha quando quiser estrutura com dissipação — firmeza que o dedo ainda molda.',
 alt='Restylane Lyft (mais projeção) · lote 27003 (ver ficha de variabilidade)'),

dict(k='Restylane Lyft Lido', m='Restylane · Galderma', t='NASHA; classe complementar de baixo SF (projeção com pouco volume)*', c='RV',
 comp='718/129/0,18 — ALTO G′ + PROJEÇÃO + PRECISÃO: o 3º maior G′ do banco, com maleabilidade NASHA.',
 mp='Projetar com precisão e pouco volume',
 ind=[('Zigoma (projeção focal)',1),('Mandíbula',1),('Mento',1),('Malar estrutural',2),('Olheira (classe SF: projeção + precisão + baixa expansão)',2),('Fossa piriforme (alerta vascular)',2),('Nariz (racional; uso seletivo — risco)',4)],
 ev=['Dinâmico superficial','Lábios'],
 esc='Escolha quando precisar de projeção real com previsibilidade volumétrica.',
 alt='Restylane Shaype (teto) · Juvéderm Volux · Yvoire Contour+'),

dict(k='Restylane Lido (lote 27003)', m='Restylane · Galderma', t='NASHA — MESMO produto do lote 22647*', c='RV', fl=['pend'],
 comp='800/206/0,26 — o mesmo Restylane, outro lote: +30% de G′. A ficha-aula do banco: variabilidade inter-lote é real e mensurável.',
 mp='Estudo de variabilidade de lote (caso didático)',
 ind=[('Uso clínico: igual ao lote 22647 — a lição aqui é metodológica',4)],
 ev=['Tratar UM número de catálogo como propriedade fixa do produto'],
 esc='Use esta ficha como argumento: número sem lote e protocolo não é número.',
 alt='Restylane Lido lote 22647 (617,71 Pa) — diferença de ~30%'),
]

# Guia rápido por região (região, classe de necessidade, produtos-síntese)
REGIOES = [
 ('Fronte / glabela / supercílio','🔵 baixo relevo','Neuramis Lido · Restylane Refyne · Biogelis Fine Lines · UP Fine','Glabela: alerta vascular máximo — reologia não é segurança.'),
 ('Têmporas','🔵/🟡 + coesividade','Belotero Volume+ · Refyne (fanning) · Volyme · Voluma · Stylage XL','Critérios de SF/coesividade sempre exigidos.'),
 ('Olheiras','🟡 baixo SF','Yvoire Contour+ · Perfectha Subskin · Restylane Lyft · Juvéderm Voluma · UP Contour','Nunca escolher pelo G′; concentração ideal ~20 mg/mL; SF ainda não medido (💧).'),
 ('Lábios — dinâmica','🔴 alto tan δ','Kysse · Neuramis Deep · Kiss · S100 · Belotero Intense · Stylage Lips · Evofill Derm · Ultra XC','Não existe "a reologia do lábio": 4 tarefas (integração, corpo, contorno, arquitetura).'),
 ('Lábios — estrutura','🟣 seletivo','Rennova Lips Plus · Volbella','"Filler labial pode ser azul ou roxo."'),
 ('Sulco nasolabial','🟢 vale + coesividade','Biogelis Volume · Deep Line · Rennova Lift · Stylage L · Cutegel CL-Max · Sofiderm Derm · Defyne','Alternativa estratégica: tratar o suporte adjacente (terço médio).'),
 ('Marionete / labiomentoniano','🟡/🟢 adaptação','S300 · Saypha Filler · Singderm · Deep Line · Fill · Outline+ · Milimetric Mod./Int.',''),
 ('Malar / bochecha (difuso)','🟢 curva','Volyme · Voluma · Belotero Volume+ · Biogelis Volume · Saypha Volume · UP Max · Sofiderm Deep · Stylage XL','Convexidade ≠ vértice.'),
 ('Zigoma (projeção focal)','🟣 vértice','Lyft · Volumax · S500 · Neuramis Volume · Saypha V. Plus · UP Contour · Yvoire Volume+ · Volux · Hyafilia V','Ponto de luz: pequenos volumes.'),
 ('Mento','🟣 corpo × vértice','Vértice: Volux · Shaype · Lift Plus · Saypha V. Plus · Hyafilia V · Lyft — Corpo: Ultra Volume · Sofiderm Deep · Stylage XL · Hyafilia Mold','MOLD modela; VOLUME projeta.'),
 ('Mandíbula / ângulo','🟣 linha + vértice','Lyft · Volux · Lift Plus · UP Contour · Hyafilia V/Mold · Stylage XL',''),
 ('Pré-jowl','vale × linha','Preencher: Deep Line · Fill · Sofiderm Derm — Construir: Lift Plus · Volux · UP Contour','Mesma região, duas tarefas.'),
 ('Fossa piriforme','🟣 suporte profundo','Volumax · S500 · Neuramis Volume · Saypha Volume/Plus · Sofiderm Deep · Hyafilia Mold','Alerta vascular.'),
 ('Nariz','🟣 projeção','Racional reológico: Volux · Shaype · Lift Plus · S500 — NUNCA 1ª escolha automática','"G′ não é segurança vascular."'),
 ('Qualidade de pele','integrar','Skinvive (microdepósitos intradérmicos)','A terceira função do AH: tratar o tecido.'),
 ('Corporal','adaptação × estrutura','Sofiderm Derm Plus (precisão) × Sub-Skin (estrutura)','"Não existe uma única reologia do preenchedor corporal."'),
]
